spring:
    application:
      name: christmas-tree
    security:
      user:
        name: admin
        password: 123456
    datasource:
      url: jdbc:postgresql://localhost:5432/lc_party_planner
      username: postgres
      password: a020210
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: holydaypartyplanner@gmail.com
        password: wybs njso nzgg vtkf
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
